baseurl = "https://username.github.io"
DefaultContentLanguage = "en"
title = "Beautiful Hugo"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "native"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClassic = false
# pygmentsOptions = "linenos=inline"
# disqusShortname = ""
eunableRobotsTXT = true
enableEmoji = true
canonifyURLs = true
enableGitInfo = true
#googleAnalytics = ""

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Build a beautiful and simple website in minutes"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  comments = false
  commit = false
#  gcse = ""
#  keywords = ["your", "keywords"]
  linkToMarkDown = false
  moreMeta = true
  postMetaInFooter = true
  readingTime = true
  WordCount = false
  rss = true
#  since = "2006"
  socialShare = true
  toc = false
  Katex = false
  Photoswipe = false
  useHLJS = true
  fancybox = true

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Some Person"
  website = "yourwebsite.com"
  email = "youremail@domain.com"
  facebook = "username"
  googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  github = "username"
  gitlab = "username"
  bitbucket = "username"
  twitter = "username"
  reddit = "username"
  linkedin = "username"
  xing = "username"
  stackoverflow = "users/XXXXXXX/username"
  snapchat = "username"
  instagram = "username"
  youtube = "user/username" # or channel/channelname
  soundcloud = "username"
  spotify = "username"
  bandcamp = "username"
  itchio = "username"
  vk = "username"
  paypal = "username"
  telegram = "username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "samples"
    name = "Samples"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Big Image Sample"
    url = "/2017/03/big-image-sample/"
    weight = 1

[[menu.main]]
    parent = "samples"
    name = "Math Sample"
    url = "/2017/03/math-sample/"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Code Sample"
    url = "/2016/03/code-sample/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
